Completed Activity Feed and Manage Orgs
GDGVIT/org-monster pull request #3
Opened 2020-11-07 20:57 UTC by RiddhiGupta5

2020-11-08 14:06 UTC, L04DB4L4NC3R requested changes

2020-11-08 14:06 UTC, L04DB4L4NC3R commented on org-monster-extension/manage-orgs.js
> +  orgsList.innerHTML += `<li class="org-tag"><span class="tag-text">${orgName}</span><span class="close">&times;</span></li>`;
XSS vulnerability alert. You are directly using user input on the same HTML without sanitizing it.

2020-11-17 10:24 UTC, Geek-ubaid commented
@RiddhiGupta5 some changes still left to be done, PR getting stale

2020-11-17 10:27 UTC, RiddhiGupta5 commented
> @RiddhiGupta5 some changes still left to be done, PR getting stale

Yeah will do the changes by tonight

2020-11-18 07:47 UTC, Geek-ubaid approved these changes

2020-11-18 07:47 UTC, Geek-ubaid commented
@L04DB4L4NC3R review the changes and merge the PR

2020-11-18 18:57 UTC, L04DB4L4NC3R approved these changes

2020-11-18 18:57 UTC, merged